// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFm-f9XtYR0pCujvP9QVZ0DVfnFnTTZOw',
    appId: '1:85421615466:web:bdd2bb54415ea61b2c9d13',
    messagingSenderId: '85421615466',
    projectId: 'complaintsnoti',
    authDomain: 'complaintsnoti.firebaseapp.com',
    storageBucket: 'complaintsnoti.firebasestorage.app',
    measurementId: 'G-EGLDEM6BM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKSTH-u6-UWUZGLe5gCUTCKI_a_tM1B4',
    appId: '1:85421615466:android:3bf1d3682de1f54a2c9d13',
    messagingSenderId: '85421615466',
    projectId: 'complaintsnoti',
    storageBucket: 'complaintsnoti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIazjgTf2ZZev9VEFmylDtkYLuqYixY-g',
    appId: '1:85421615466:ios:de6094d62e91039a2c9d13',
    messagingSenderId: '85421615466',
    projectId: 'complaintsnoti',
    storageBucket: 'complaintsnoti.firebasestorage.app',
    iosBundleId: 'com.example.shakwa',
  );
}
